# Домашняя работа №3.
                              
>* Имя файла: ``HW3_Imanaliyeva_Aminat.ipynb``
>* Автор и учебная группа: ``Иманалиева Аминат, мАДБМ-251``
>* Дата создания: ``30.09.2025``
>* Дата последней модификации:  ``01.10.2025``
>* Связанные файлы: ``отсутствуют``
>* Версия Python: ``3.10.10``
>* Описание: ``решение задач из домашней работы``

## Нидлман-Вунш

In [1]:
#!/usr/bin/env python3
"""
Алгоритма Нидлмана-Вунша.
"""

import time
import os


def clear_screen():
    """Очищает экран"""
    os.system('clear' if os.name == 'posix' else 'cls')


def print_matrix(seq1, seq2, dp, current_i=None, current_j=None, step_info=""):
    """
    Печатает матрицу с анимацией текущей ячейки
    """
    clear_screen()

    print("=" * 70)
    print("АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ")
    print("=" * 70)
    print(f"Seq1: {seq1}")
    print(f"Seq2: {seq2}")
    if step_info:
        print(f"Шаг: {step_info}")
    print()

    # Заголовок
    print("     ", end="")
    for j in range(len(dp[0])):
        if j == 0:
            print("   ", end="")
        else:
            print(f"  {seq2[j-1]}", end="")
    print()

    # Строки матрицы
    for i in range(len(dp)):
        if i == 0:
            print("   ", end="")
        else:
            print(f" {seq1[i-1]} ", end="")

        for j in range(len(dp[0])):
            # Выделяем текущую ячейку
            if current_i == i and current_j == j:
                print(f"[{dp[i][j]:2}]", end="")
            else:
                print(f" {dp[i][j]:2} ", end="")
        print()

    print("=" * 70)


def needleman_wunsch(seq1, seq2, match=2, mismatch=-1, gap=-1):
    """
    Алгоритма Нидлмана-Вунша
    """
    n, m = len(seq1), len(seq2)


    dp = [[0] * (m+1) for _ in range(n+1)]

    for i in range(n+1):
        dp[i][0] = i * gap
    for j in range(m+1):
        dp[0][j] = j * gap

    print_matrix(seq1, seq2, dp, step_info="Инициализация")
    time.sleep(2)

    for i in range(1, n+1):
        for j in range(1, m+1):
            print_matrix(seq1, seq2, dp, current_i=i, current_j=j,
                                step_info=f"Заполнение ячейки ({i},{j})")

            match_score = dp[i-1][j-1] + (match if seq1[i-1] == seq2[j-1] else mismatch)
            delete = dp[i-1][j] + gap
            insert = dp[i][j-1] + gap

            print(f"\nРасчет для {seq1[i-1]} vs {seq2[j-1]}:")
            print(f"↖ Совпадение: {dp[i-1][j-1]} + {match if seq1[i-1] == seq2[j-1] else '-1'} = {match_score}")
            print(f"↑ Удаление:   {dp[i-1][j]} + {gap} = {delete}")
            print(f"← Вставка:    {dp[i][j-1]} + {gap} = {insert}")

            dp[i][j] = max(match_score, delete, insert)

            print(f"Максимум: {dp[i][j]}")
            time.sleep(1.5)

    print_matrix(seq1, seq2, dp, step_info="Матрица заполнена")
    time.sleep(2)

    align1, align2 = "", ""
    i, j = n, m

    print("\nОБРАТНЫЙ ПРОХОД:")
    print("=" * 50)

    step = 1
    while i > 0 or j > 0:
        print(f"\nШаг {step}: Позиция ({i},{j})")

        if i > 0 and j > 0 and dp[i][j] == dp[i-1][j-1] + (match if seq1[i-1] == seq2[j-1] else mismatch):
            print(f"  ↖ Совпадение: {seq1[i-1]} = {seq2[j-1]}")
            align1 = seq1[i-1] + align1
            align2 = seq2[j-1] + align2
            i -= 1
            j -= 1
        elif i > 0 and dp[i][j] == dp[i-1][j] + gap:
            print(f"  ↑ Удаление: {seq1[i-1]} → -")
            align1 = seq1[i-1] + align1
            align2 = "-" + align2
            i -= 1
        else:
            print(f"  ← Вставка: - ← {seq2[j-1]}")
            align1 = "-" + align1
            align2 = seq2[j-1] + align2
            j -= 1

        print(f"  Выравнивание: {align1}")
        print(f"                {align2}")

        step += 1
        time.sleep(1)

    return align1, align2, dp


def main():
    """
    Демонстрация алгоритма
    """
    # Ваши последовательности
    seq1 = "GCATGCG"
    seq2 = "GATTACA"

    print("АЛГОРИТМ НИДЛМАНА-ВУНША")
    print("=" * 70)
    print(f"Последовательность 1: {seq1}")
    print(f"Последовательность 2: {seq2}")
    print("Параметры: match=2, mismatch=-1, gap=-1")
    print()

    result1, result2, matrix = needleman_wunsch(seq1, seq2)

    print("\n" + "=" * 70)
    print("ФИНАЛЬНЫЙ РЕЗУЛЬТАТ:")
    print("=" * 70)
    print(f"Выравнивание 1: {result1}")
    print(f"Выравнивание 2: {result2}")
    print(f"Общий score: {matrix[len(seq1)][len(seq2)]}")


if __name__ == "__main__":
    main()


АЛГОРИТМ НИДЛМАНА-ВУНША
Последовательность 1: GCATGCG
Последовательность 2: GATTACA
Параметры: match=2, mismatch=-1, gap=-1

АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Инициализация

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1   0   0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 
АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Заполнение ячейки (1,1)

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1 [ 0]  0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 

Расчет для G vs G:
↖ Совпадение: 0 + 2

**Aлгоритм** ищет путь, который балансирует между *максимизацией* совпадений и *минимизацией* штрафов за несовпадения и пропуски.

# Самостоятельная работа

#  Часть 1

In [ ]:
# 1. Объясните, чему будет равно значение в ячейке (1, 2). Почему?

# Параметры:
# Match = +2
# Mismatch = -1
# Gap = -1

мы выбираем максимальное число из трех вариантов на каждом элементе:

```
score(i,j) = max(
    score(i-1,j-1) + (Match если символы совпадают, иначе Mismatch),
    score(i-1,j) + Gap,
    score(i,j-1) + Gap,)
```
ну из-за того что мы стоим на 2 строке 3 столбце, у нас есть три пути прохождения. зависит от макс скора в этой ячейке


In [ ]:
# Создание матрицы:

import numpy as np

# Создание матрицы 5x5 с числами от 1 до 25
matrix = np.arange(1, 26).reshape(5, 5)
print("Исходная матрица:")
print(matrix)

Исходная матрица:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [92]:
# Задание 3: Элемент сверху для каждой ячейки

# Напишите код, который для каждой  ячейки матрицы выведет элемент,
# находящийся непосредственно над ней (сверху).
# Начинайте с элемента (1,1) и двигайтесь последовательно по строкам, пропуская элементы в нулевой строке и в нулевом столбце

# Требования:

#     Для каждой ячейки выводите ее координаты

#     Выводите элемент сверху



# Пример вывода для первых нескольких ячеек:

# Ячейка (2,1) = 6 → Сверху: 1
# Ячейка (2,2) = 7 → Сверху: 2

for i in range(1, len(matrix)):
    for j in range(1, len(matrix[i])):
        current_value = matrix[i][j]
        top_value = matrix[i-1][j]  # элемент сверху

        print(f" ({i},{j}) = {current_value},  cверху: {top_value}")

 (1,1) = 5,  cверху: 2
 (1,2) = 6,  cверху: 3
 (2,1) = 8,  cверху: 5
 (2,2) = 9,  cверху: 6


In [86]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
# Задание 2: Элемент по диагонали (левый верхний) для каждой ячейки

# Задача: Напишите код, который для каждой ячейки матрицы выведет элемент, находящийся по диагонали слева сверху.
# Начинайте с элемента (1,1)

# Требования:

#     Для каждой ячейки выводите ее координаты и значение

#     Выводите диагональный элемент, если он существует

#     Если диагонального элемента не существует (для первой строки или первого столбца), выводите соответствующее сообщение

for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        current_value = matrix[i][j]

        if i > 0 and j > 0:
            diagonal_value = matrix[i-1][j-1]
            print(f" ({i+1},{j+1}) = {current_value:2}, diag : {diagonal_value}")
        elif i == 0 and j == 0:
            print(f" ({i+1},{j+1}) = {current_value:2}, первая ячейка")
        elif i == 0:
            print(f" ({i+1},{j+1}) = {current_value:2}, нет элемента сверху")
        else:  # j == 0
            print(f" ({i+1},{j+1}) = {current_value:2}, нет элемента слева")

 (1,1) =  1, первая ячейка
 (1,2) =  2, нет элемента сверху
 (1,3) =  3, нет элемента сверху
 (2,1) =  4, нет элемента слева
 (2,2) =  5, diag : 1
 (2,3) =  6, diag : 2
 (3,1) =  7, нет элемента слева
 (3,2) =  8, diag : 4
 (3,3) =  9, diag : 5


In [97]:
# Задание 3: Элемент слева для каждой ячейки

# Задача: Напишите код, который для каждой  ячейки матрицы выведет элемент, находящийся непосредственно слева.

# Начинайте с элемента (1,1)

# Требования:

#     Для каждой ячейки выводите ее координаты и значение

#     Выводите левый элемент

for i in range(1, len(matrix)):
    for j in range(1, len(matrix[i])):
        current_value = matrix[i][j]
        top_value = matrix[i][j-1]
        print(f" ({i},{j}) = {current_value},  слева: {top_value}")


 (1,1) = 5,  слева: 4
 (1,2) = 6,  слева: 5
 (2,1) = 8,  слева: 7
 (2,2) = 9,  слева: 8


In [98]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Часть 2

In [7]:
# 1. NumPy: создайте матрицу от 1 до 9
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 2. NumPy: создайте матрицу от 9 до 1
np.arange(9,0,-1).reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [12]:
# 3. NumPy: транспонируйте матрицу
np.transpose(matrix)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
# 3. NumPy: транспонируйте матрицу
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
# 4. NumPy: создайте 2 матрицы и сложите их
A  = np.arange(1,9).reshape(2,4)
B  = np.arange(10,18).reshape(2,4)
A+B

array([[11, 13, 15, 17],
       [19, 21, 23, 25]])

In [28]:
# 5. NumPy: создайте 2 матрицы и перемножьте их
# можем если совпадают внутренние размеры
K = np.arange(1,9).reshape(4,2)
np.dot(A,K)

array([[ 50,  60],
       [114, 140]])

In [29]:
# 6. Используя NumPy создайте единичную матрицу (по главной диагонали единицы)

# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Домашнее задание

In [2]:
# 1. Вам представлен код с реализацией алгоритма Нидлмана-Вунша. Функция needleman_wunsch принимает параметры: match=2, mismatch=-1, gap=-1
# поэксперементируйте с параметрами и посморите, как меняется выравнивание и score. Какие выводы можно сделать?

def needleman_wunsch(seq1, seq2, match=2, mismatch=-1, gap=-1):
    """
    Алгоритма Нидлмана-Вунша
    """
    n, m = len(seq1), len(seq2)


    dp = [[0] * (m+1) for _ in range(n+1)]

    for i in range(n+1):
        dp[i][0] = i * gap
    for j in range(m+1):
        dp[0][j] = j * gap

    print_matrix(seq1, seq2, dp, step_info="Инициализация")
    time.sleep(2)

    for i in range(1, n+1):
        for j in range(1, m+1):
            print_matrix(seq1, seq2, dp, current_i=i, current_j=j,
                                step_info=f"Заполнение ячейки ({i},{j})")

            match_score = dp[i-1][j-1] + (match if seq1[i-1] == seq2[j-1] else mismatch)
            delete = dp[i-1][j] + gap
            insert = dp[i][j-1] + gap

            print(f"\nРасчет для {seq1[i-1]} vs {seq2[j-1]}:")
            print(f"↖ Совпадение: {dp[i-1][j-1]} + {match if seq1[i-1] == seq2[j-1] else '-1'} = {match_score}")
            print(f"↑ Удаление:   {dp[i-1][j]} + {gap} = {delete}")
            print(f"← Вставка:    {dp[i][j-1]} + {gap} = {insert}")

            dp[i][j] = max(match_score, delete, insert)

            print(f"Максимум: {dp[i][j]}")
            time.sleep(1.5)

    print_matrix(seq1, seq2, dp, step_info="Матрица заполнена")
    time.sleep(2)

    align1, align2 = "", ""
    i, j = n, m

    print("\nОБРАТНЫЙ ПРОХОД:")
    print("=" * 50)

    step = 1
    while i > 0 or j > 0:
        print(f"\nШаг {step}: Позиция ({i},{j})")

        if i > 0 and j > 0 and dp[i][j] == dp[i-1][j-1] + (match if seq1[i-1] == seq2[j-1] else mismatch):
            print(f"  ↖ Совпадение: {seq1[i-1]} = {seq2[j-1]}")
            align1 = seq1[i-1] + align1
            align2 = seq2[j-1] + align2
            i -= 1
            j -= 1
        elif i > 0 and dp[i][j] == dp[i-1][j] + gap:
            print(f"  ↑ Удаление: {seq1[i-1]} → -")
            align1 = seq1[i-1] + align1
            align2 = "-" + align2
            i -= 1
        else:
            print(f"  ← Вставка: - ← {seq2[j-1]}")
            align1 = "-" + align1
            align2 = seq2[j-1] + align2
            j -= 1

        print(f"  Выравнивание: {align1}")
        print(f"                {align2}")

        step += 1
        time.sleep(1)

    return align1, align2, dp

In [38]:
seq1 = "GCATGCG"
seq2 = "GATTACA"

In [44]:
# награда за match
needleman_wunsch(seq1, seq2,5,-1,-1)

АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Инициализация

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1   0   0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 
АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Заполнение ячейки (1,1)

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1 [ 0]  0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 

Расчет для G vs G:
↖ Совпадение: 0 + 5 = 5
↑ Удаление:   -1 + -1 = -2
← Вставка:    -1 + -1 = -2
Максимум: 5
АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: G

('GCA-TGCG',
 'G-ATTACA',
 [[0, -1, -2, -3, -4, -5, -6, -7],
  [-1, 5, 4, 3, 2, 1, 0, -1],
  [-2, 4, 4, 3, 2, 1, 6, 5],
  [-3, 3, 9, 8, 7, 7, 6, 11],
  [-4, 2, 8, 14, 13, 12, 11, 10],
  [-5, 1, 7, 13, 13, 12, 11, 10],
  [-6, 0, 6, 12, 12, 12, 17, 16],
  [-7, -1, 5, 11, 11, 11, 16, 16]])

In [ ]:
#score = 16

In [45]:
# увеличим штраф за mismatch (match=2, mismatch=-5, gap=-1)
needleman_wunsch(seq1, seq2,2,-5,-1)

АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Инициализация

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1   0   0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 
АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Заполнение ячейки (1,1)

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1 [ 0]  0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 

Расчет для G vs G:
↖ Совпадение: 0 + 2 = 2
↑ Удаление:   -1 + -1 = -2
← Вставка:    -1 + -1 = -2
Максимум: 2
АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: G

('GCA-T-GC-G',
 'G-ATTA-CA-',
 [[0, -1, -2, -3, -4, -5, -6, -7],
  [-1, 2, 1, 0, -1, -2, -3, -4],
  [-2, 1, 0, -1, -2, -3, 0, -1],
  [-3, 0, 3, 2, 1, 0, -1, 2],
  [-4, -1, 2, 5, 4, 3, 2, 1],
  [-5, -2, 1, 4, 3, 2, 1, 0],
  [-6, -3, 0, 3, 2, 1, 4, 3],
  [-7, -4, -1, 2, 1, 0, 3, 2]])

In [ ]:
# score = 2

In [46]:
#увеличим штраф за гэп
needleman_wunsch(seq1, seq2, 2, -1, -5)


АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Инициализация

          G  A  T  T  A  C  A
     0  -5  -10  -15  -20  -25  -30  -35 
 G  -5   0   0   0   0   0   0   0 
 C  -10   0   0   0   0   0   0   0 
 A  -15   0   0   0   0   0   0   0 
 T  -20   0   0   0   0   0   0   0 
 G  -25   0   0   0   0   0   0   0 
 C  -30   0   0   0   0   0   0   0 
 G  -35   0   0   0   0   0   0   0 
АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Заполнение ячейки (1,1)

          G  A  T  T  A  C  A
     0  -5  -10  -15  -20  -25  -30  -35 
 G  -5 [ 0]  0   0   0   0   0   0 
 C  -10   0   0   0   0   0   0   0 
 A  -15   0   0   0   0   0   0   0 
 T  -20   0   0   0   0   0   0   0 
 G  -25   0   0   0   0   0   0   0 
 C  -30   0   0   0   0   0   0   0 
 G  -35   0   0   0   0   0   0   0 

Расчет для G vs G:
↖ Совпадение: 0 + 2 = 2
↑ Удаление:   -5 + -5 = -10
← Вставка:    -5 + -5 = -10
Максимум: 2
АЛГОРИТМ НИДЛМАНА-ВУНША - ПО

('GCATGCG',
 'GATTACA',
 [[0, -5, -10, -15, -20, -25, -30, -35],
  [-5, 2, -3, -8, -13, -18, -23, -28],
  [-10, -3, 1, -4, -9, -14, -16, -21],
  [-15, -8, -1, 0, -5, -7, -12, -14],
  [-20, -13, -6, 1, 2, -3, -8, -13],
  [-25, -18, -11, -4, 0, 1, -4, -9],
  [-30, -23, -16, -9, -5, -1, 3, -2],
  [-35, -28, -21, -14, -10, -6, -2, 2]])

Я привела оставила пример трех разных вариаций, но в целом можно сказать, что:  

1. При слишком высокой оценке mathc, увеличивается общий score, но выравнивание не меняется
2. Если gap  слишком низкое относительно mismatch, алгоритм будет предпочитать вставлять gaps вместо принятия mismatches, и тогда наша последовательность по выравниванию полупустая (забита гэпами)
3. Если gap слишком высокий, то алгоритм предпочитает принять mismatches, чем создавать много пропусков

**Вывод: и тогда мы видим, что относительные значения важнее абсолютных - имеет значение соотношение между match, mismatch и gap.**

In [32]:
# 2. Используя numpy создайте матрицу 7 на 7

np.arange(1,50).reshape(7,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [33]:
# 3. NumPy: создайтие диагональную матрицу, где по главной диагонали идут числа от 1 до 5

np.diag(range(1,6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [79]:
# 4. Напиши функцию, которая принимает матрицу и проверяет, является ли она единичной. В ответе возвращается True или False

def check_matrix(matrix):
    n = len(matrix)

    for i in range(n):
        for j in range(n):
            if i == j:
                if matrix[i][j] != 1:
                    return False
            else:
                if matrix[i][j] != 0:
                    return False

    return True

In [80]:
ex1 = np.diag(range(1,6))
ex2 = np.arange(1,50).reshape(7,7)
ex3 = np.eye(5)

In [83]:
check_matrix(ex3)

True

In [84]:
check_matrix(ex2)

False